[
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48674",
    "id": 1380183854,
    "node_id": "I_kwDOAA0YD85SQ-8u",
    "number": 48674,
    "title": "BUG: Wrong index constructor if new DF/Series is created from DF/Series",
    "user": {
      "login": "MichalRIcar",
      "id": 62614119,
      "node_id": "MDQ6VXNlcjYyNjE0MTE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/62614119?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MichalRIcar",
      "html_url": "https://github.com/MichalRIcar",
      "followers_url": "https://api.github.com/users/MichalRIcar/followers",
      "following_url": "https://api.github.com/users/MichalRIcar/following{/other_user}",
      "gists_url": "https://api.github.com/users/MichalRIcar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MichalRIcar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MichalRIcar/subscriptions",
      "organizations_url": "https://api.github.com/users/MichalRIcar/orgs",
      "repos_url": "https://api.github.com/users/MichalRIcar/repos",
      "events_url": "https://api.github.com/users/MichalRIcar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MichalRIcar/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-21T01:28:09Z",
    "updated_at": "2022-09-21T01:28:09Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nfrom pandas import DataFrame as pDF, Series as pSe\r\n\r\n# INIT\r\n# ────────────────────────────────────────────────────────────\r\n# DATA\r\nx = pDF({'A':[1,2,3,4],'B':[5,6,7,8]}, index=[1,0,1,0])\r\n\r\n# NEW VAR TO BE ADDED IN SEVERAL WAYS\r\nN = [1,2,3,4]\r\n\r\n\r\n# (1) Works as expected → New variable from a List\r\n# ────────────────────────────────────────────────────────────\r\nx['N'] = N\r\n\r\n# (1) RESULT → OK\r\n\tA\tB\tN\r\n1\t1\t5\t1\r\n0\t2\t6\t2\r\n1\t3\t7\t3\r\n0\t4\t8\t4\r\n\r\n\r\n# (2) Works as expected → New variable from pSe/PDF\r\n# ────────────────────────────────────────────────────────────\r\nx['N'] = pDF(N, index=x.index)\r\n# OR \r\nx['N'] = pSe(N, index=x.index)\r\n# Produces the same correct result\r\n\r\n# (2) RESULT → OK\r\n\tA\tB\tN\r\n1\t1\t5\t1\r\n0\t2\t6\t2\r\n1\t3\t7\t3\r\n0\t4\t8\t4\r\n\r\n# (3) DOESN'T Work as expected → New variable from ► INNER pSe/PDF ◄\r\n# ────────────────────────────────────────────────────────────\r\nx['N'] = pDF(pSe(N), index=x.index)\r\n# OR \r\nx['N'] = pSe(pSe(N), index=x.index)\r\n# Produces WRONG Result as index mismatch\r\n\r\n# (3) RESULT → WRONG → INDEX MISMATCH\r\n\tA\tB\tN\r\n1\t1\t5\t2\r\n0\t2\t6\t1\r\n1\t3\t7\t2\r\n0\t4\t8\t1\r\n\r\n# (4) WRONG behavior can be overcome by using set_index as follows:\r\nx['N'] = pDF(pSe(N)).set_index(x.index)\r\n# Which produces correct result\n```\n\n\n### Issue Description\n\nWorking with variables, and creating new variables is a crucial component of pandas. \r\nThus I assume that the construct of the new variable should be consistent regardless of using index= or set_index() method.\r\n\r\nThe example above shows that issue is inside the constructor when an inner dataframe or series is used and a non-unique index is present in the targeted dataframe → in such a situation using index= param during the constructor doesn't work as expected and it is inconsistent with the rest of the approachs.\n\n### Expected Behavior\n\nConsistent behavior of constructor for index= and set_index regardless of input object to DataFrame/Serie.\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : e8093ba372f9adfe79439d90fe74b0b5b6dea9d6\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19043\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.4.3\r\nnumpy            : 1.20.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\nsetuptools       : 58.0.4\r\npip              : 21.2.4\r\nCython           : 0.29.24\r\npytest           : 6.2.4\r\nhypothesis       : None\r\nsphinx           : 4.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.1\r\nlxml.etree       : 4.6.3\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.3\r\nIPython          : 7.29.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : 1.3.2\r\nbrotli           : \r\nfastparquet      : None\r\nfsspec           : 2021.10.1\r\ngcsfs            : None\r\nmarkupsafe       : 1.1.1\r\nmatplotlib       : 3.5.2\r\nnumba            : 0.54.1\r\nnumexpr          : 2.7.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsnappy           : None\r\nsqlalchemy       : 1.4.22\r\ntables           : 3.6.1\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nzstandard        : None\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48674/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48673",
    "id": 1380171014,
    "node_id": "I_kwDOAA0YD85SQ70G",
    "number": 48673,
    "title": "BUG: Unclear FutureWarning regarding inplace iloc setitem",
    "user": {
      "login": "mwaskom",
      "id": 315810,
      "node_id": "MDQ6VXNlcjMxNTgxMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/315810?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mwaskom",
      "html_url": "https://github.com/mwaskom",
      "followers_url": "https://api.github.com/users/mwaskom/followers",
      "following_url": "https://api.github.com/users/mwaskom/following{/other_user}",
      "gists_url": "https://api.github.com/users/mwaskom/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mwaskom/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mwaskom/subscriptions",
      "organizations_url": "https://api.github.com/users/mwaskom/orgs",
      "repos_url": "https://api.github.com/users/mwaskom/repos",
      "events_url": "https://api.github.com/users/mwaskom/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mwaskom/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-09-21T01:09:41Z",
    "updated_at": "2022-09-21T01:11:36Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport numpy as np, pandas as pd\r\nvalues = np.arange(4).reshape(2, 2)\r\ndf = pd.DataFrame(values, columns=[\"a\", \"b\"])\r\nnew = np.array([10, 11]).astype(np.int16)\r\ndf.loc[:, \"a\"] = new\n```\n\n\n### Issue Description\n\n> FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`\r\n\r\nThis is confusing because I did not do `df.iloc`, I did `df.loc`. In the [release notes](https://pandas.pydata.org/docs/whatsnew/v1.5.0.html#inplace-operation-when-setting-values-with-loc-and-iloc), the subsection header mentions `.loc`, but the text only talks about `.iloc`.\r\n\r\nAdditionally, it was very difficult to put together a reproducible example, until I found a related issue demonstrating that it matters whether the old/new series have different dtypes. This is reasonably clear from the release notes themselves, but not the warning message.\n\n### Expected Behavior\n\nI assume that this change does affect both `.loc` and `.iloc` so the warning message could be updated to be more clear, but in the event it's a false alarm on `.loc`, it would be good to suppress it.\r\n\r\nThe warning message could also be a little bit more clear about why the warning got triggered (even if in a general sense).\n\n### Installed Versions\n\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.10.0.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.6.0\r\nVersion          : Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110\r\nmachine          : arm64\r\nprocessor        : arm\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.23.3\r\npytz             : 2022.2.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 63.4.1\r\npip              : 22.1.2\r\nCython           : None\r\npytest           : 7.1.3\r\nhypothesis       : None\r\nsphinx           : 5.1.1\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.1.2\r\nIPython          : 8.5.0\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.6.0\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.9.1\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48673/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48672",
    "id": 1380167311,
    "node_id": "PR_kwDOAA0YD84_UEMr",
    "number": 48672,
    "title": "DOC: Document default value for options.display.max_cols when not running in terminal",
    "user": {
      "login": "tmoschou",
      "id": 5567550,
      "node_id": "MDQ6VXNlcjU1Njc1NTA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5567550?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tmoschou",
      "html_url": "https://github.com/tmoschou",
      "followers_url": "https://api.github.com/users/tmoschou/followers",
      "following_url": "https://api.github.com/users/tmoschou/following{/other_user}",
      "gists_url": "https://api.github.com/users/tmoschou/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tmoschou/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tmoschou/subscriptions",
      "organizations_url": "https://api.github.com/users/tmoschou/orgs",
      "repos_url": "https://api.github.com/users/tmoschou/repos",
      "events_url": "https://api.github.com/users/tmoschou/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tmoschou/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-21T01:04:04Z",
    "updated_at": "2022-09-21T01:06:13Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48672",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48672",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48672.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48672.patch",
      "merged_at": null
    },
    "body": "`display.max_cols` has a default value of 20 when not running in a terminal such as Jupyter Notebook.\r\n\r\nThis was a little confusing as the documentation for the default parameters generated in [Pandas User Guide - Available Options](https://pandas.pydata.org/docs/user_guide/options.html#available-options) are [environment specific](https://github.com/pandas-dev/pandas/blob/e493323d93e6a3447f0adfded493b80a42f4fec4/pandas/core/config_init.py#L412-L415) and 0 for when terminal is detected, but this was not noted in the current description.\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48672/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48671",
    "id": 1380103084,
    "node_id": "PR_kwDOAA0YD84_T3GC",
    "number": 48671,
    "title": "DEPR: enforce deprecation on floats with unit=M or Y",
    "user": {
      "login": "jbrockmendel",
      "id": 8078968,
      "node_id": "MDQ6VXNlcjgwNzg5Njg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbrockmendel",
      "html_url": "https://github.com/jbrockmendel",
      "followers_url": "https://api.github.com/users/jbrockmendel/followers",
      "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
      "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
      "repos_url": "https://api.github.com/users/jbrockmendel/repos",
      "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T23:25:59Z",
    "updated_at": "2022-09-20T23:25:59Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48671",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48671",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48671.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48671.patch",
      "merged_at": null
    },
    "body": "Unfortunately just found that we missed the analogous behavior in to_datetime with non-scalars.  That'll go in the just-do-in-2.0 pile.\r\n\r\nWhatsnew is in 1.6 on the assumption it will be changed to 2.0.",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48671/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48670",
    "id": 1380066465,
    "node_id": "PR_kwDOAA0YD84_Tvnz",
    "number": 48670,
    "title": "ENH: unique/factorize preserve non-nano",
    "user": {
      "login": "jbrockmendel",
      "id": 8078968,
      "node_id": "MDQ6VXNlcjgwNzg5Njg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbrockmendel",
      "html_url": "https://github.com/jbrockmendel",
      "followers_url": "https://api.github.com/users/jbrockmendel/followers",
      "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
      "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
      "repos_url": "https://api.github.com/users/jbrockmendel/repos",
      "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T22:28:10Z",
    "updated_at": "2022-09-20T22:28:10Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48670",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48670",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48670.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48670.patch",
      "merged_at": null
    },
    "body": "Put the whatsnew note in 1.6, assuming that will be changed to 2.0.",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48670/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48669",
    "id": 1380005973,
    "node_id": "PR_kwDOAA0YD84_Ti4m",
    "number": 48669,
    "title": "ENH: DTA/TDA add datetimelike scalar with mismatched reso",
    "user": {
      "login": "jbrockmendel",
      "id": 8078968,
      "node_id": "MDQ6VXNlcjgwNzg5Njg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbrockmendel",
      "html_url": "https://github.com/jbrockmendel",
      "followers_url": "https://api.github.com/users/jbrockmendel/followers",
      "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
      "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
      "repos_url": "https://api.github.com/users/jbrockmendel/repos",
      "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T21:17:04Z",
    "updated_at": "2022-09-20T22:46:24Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48669",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48669",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48669.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48669.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48669/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48667",
    "id": 1379970770,
    "node_id": "I_kwDOAA0YD85SQK7S",
    "number": 48667,
    "title": "BUG: to_hdf fails with boolean index in 1.5",
    "user": {
      "login": "anthonyaag",
      "id": 6341861,
      "node_id": "MDQ6VXNlcjYzNDE4NjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6341861?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/anthonyaag",
      "html_url": "https://github.com/anthonyaag",
      "followers_url": "https://api.github.com/users/anthonyaag/followers",
      "following_url": "https://api.github.com/users/anthonyaag/following{/other_user}",
      "gists_url": "https://api.github.com/users/anthonyaag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/anthonyaag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/anthonyaag/subscriptions",
      "organizations_url": "https://api.github.com/users/anthonyaag/orgs",
      "repos_url": "https://api.github.com/users/anthonyaag/repos",
      "events_url": "https://api.github.com/users/anthonyaag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/anthonyaag/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      },
      {
        "id": 47229190,
        "node_id": "MDU6TGFiZWw0NzIyOTE5MA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20HDF5",
        "name": "IO HDF5",
        "color": "5319e7",
        "default": false,
        "description": "read_hdf, HDFStore"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2022-09-20T20:41:21Z",
    "updated_at": "2022-09-21T00:09:42Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\npd.DataFrame([[False, 1]], columns=[\"a\", \"b\"]).set_index(['a']).to_hdf(\"/tmp/a.hdf\", \"a\")\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nWhen saving to_hdf a dataframe which has a boolean index I get an assertion error from inside pytables \r\n\r\n```\r\n   4943     return IndexCol(\r\n   4944         name, values=converted, kind=kind, typ=atom, index_name=index_name\r\n   4945     )\r\n   4946 else:\r\n-> 4947     assert isinstance(converted, np.ndarray) and converted.dtype == object\r\n   4948     assert kind == \"object\", kind\r\n   4949     atom = _tables().ObjectAtom()\r\n\r\nAssertionError:\r\n```\r\n\r\nHowever, when saving a dataframe with no boolean in the index this works as expected.\r\n\r\nAdditionally saving dataframes with booleans in the index worked in 1.4.4\r\n\r\n### Expected Behavior\r\n\r\n```\r\nimport pandas as pd\r\npd.DataFrame([[False, 1]], columns=[\"a\", \"b\"]).set_index(['a']).to_hdf(\"/tmp/a.hdf\", \"a\")\r\n```\r\nworks identically to \r\n```\r\nimport pandas as pd\r\npd.DataFrame([['False', 1]], columns=[\"a\", \"b\"]).set_index(['a']).to_hdf(\"/tmp/a.hdf\", \"a\")\r\n```\r\n\r\n### Installed Versions\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.10.7.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.4.117.hrtdev\r\nVersion          : #3 SMP Tue May 11 13:44:03 EDT 2021\r\nmachine          : x86_64\r\nprocessor        :\r\nbyteorder        : little\r\nLC_ALL           :\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.23.2\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 62.1.0\r\npip              : 22.2.2\r\nCython           : 0.29.30\r\npytest           : 7.1.2\r\nhypothesis       : 6.52.3\r\nsphinx           : 5.0.2\r\nblosc            : 1.10.6\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : 1.1\r\npymysql          : 1.0.2\r\npsycopg2         : 2.9.3\r\njinja2           : 3.1.2\r\nIPython          : 8.4.0\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : 1.3.5\r\nbrotli           : 1.0.9\r\nfastparquet      : 0.8.1\r\nfsspec           : 2022.5.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.2\r\nnumba            : 0.56.2\r\nnumexpr          : 2.8.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.10\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : 1.0.9\r\ns3fs             : None\r\nscipy            : 1.9.1\r\nsnappy           : None\r\nsqlalchemy       : 1.4.39\r\ntables           : 3.7.0\r\ntabulate         : 0.8.10\r\nxarray           : 2022.6.0\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : 0.18.0\r\ntzdata           : 2022.1",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48667/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48666",
    "id": 1379848504,
    "node_id": "PR_kwDOAA0YD84_TCGg",
    "number": 48666,
    "title": "Backport PR #48651 on branch 1.5.x (REGR: TextIOWrapper raising an error in read_csv)",
    "user": {
      "login": "meeseeksmachine",
      "id": 39504233,
      "node_id": "MDQ6VXNlcjM5NTA0MjMz",
      "avatar_url": "https://avatars.githubusercontent.com/u/39504233?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/meeseeksmachine",
      "html_url": "https://github.com/meeseeksmachine",
      "followers_url": "https://api.github.com/users/meeseeksmachine/followers",
      "following_url": "https://api.github.com/users/meeseeksmachine/following{/other_user}",
      "gists_url": "https://api.github.com/users/meeseeksmachine/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/meeseeksmachine/subscriptions",
      "organizations_url": "https://api.github.com/users/meeseeksmachine/orgs",
      "repos_url": "https://api.github.com/users/meeseeksmachine/repos",
      "events_url": "https://api.github.com/users/meeseeksmachine/events{/privacy}",
      "received_events_url": "https://api.github.com/users/meeseeksmachine/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 47229171,
        "node_id": "MDU6TGFiZWw0NzIyOTE3MQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV",
        "name": "IO CSV",
        "color": "5319e7",
        "default": false,
        "description": "read_csv, to_csv"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 0,
    "created_at": "2022-09-20T18:46:26Z",
    "updated_at": "2022-09-20T18:46:27Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48666",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48666",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48666.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48666.patch",
      "merged_at": null
    },
    "body": "Backport PR #48651: REGR: TextIOWrapper raising an error in read_csv",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48666/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48665",
    "id": 1379820309,
    "node_id": "I_kwDOAA0YD85SPmMV",
    "number": 48665,
    "title": "BUG: None value converted to NaN in Series",
    "user": {
      "login": "stephanecollot",
      "id": 1184396,
      "node_id": "MDQ6VXNlcjExODQzOTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1184396?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stephanecollot",
      "html_url": "https://github.com/stephanecollot",
      "followers_url": "https://api.github.com/users/stephanecollot/followers",
      "following_url": "https://api.github.com/users/stephanecollot/following{/other_user}",
      "gists_url": "https://api.github.com/users/stephanecollot/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stephanecollot/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stephanecollot/subscriptions",
      "organizations_url": "https://api.github.com/users/stephanecollot/orgs",
      "repos_url": "https://api.github.com/users/stephanecollot/repos",
      "events_url": "https://api.github.com/users/stephanecollot/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stephanecollot/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 2822098,
        "node_id": "MDU6TGFiZWwyODIyMDk4",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Indexing",
        "name": "Indexing",
        "color": "0b02e1",
        "default": false,
        "description": "Related to indexing on series/frames, not to indexes themselves"
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "phofl",
      "id": 61934744,
      "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/phofl",
      "html_url": "https://github.com/phofl",
      "followers_url": "https://api.github.com/users/phofl/followers",
      "following_url": "https://api.github.com/users/phofl/following{/other_user}",
      "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
      "organizations_url": "https://api.github.com/users/phofl/orgs",
      "repos_url": "https://api.github.com/users/phofl/repos",
      "events_url": "https://api.github.com/users/phofl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/phofl/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "phofl",
        "id": 61934744,
        "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
        "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/phofl",
        "html_url": "https://github.com/phofl",
        "followers_url": "https://api.github.com/users/phofl/followers",
        "following_url": "https://api.github.com/users/phofl/following{/other_user}",
        "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
        "organizations_url": "https://api.github.com/users/phofl/orgs",
        "repos_url": "https://api.github.com/users/phofl/repos",
        "events_url": "https://api.github.com/users/phofl/events{/privacy}",
        "received_events_url": "https://api.github.com/users/phofl/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 1,
    "created_at": "2022-09-20T18:19:59Z",
    "updated_at": "2022-09-20T20:31:03Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\n>>> import pandas as pd\r\n>>> s = pd.Series(['a', 'b'])\r\n>>> s\r\n0    a\r\n1    b\r\ndtype: object\r\n>>> s['a'] = None\r\n>>> s\r\n0      a\r\n1      b\r\na    NaN\r\ndtype: object\n```\n\n\n### Issue Description\n\nIn 1.5.0 there is a behaviour change, if you set a value on a Serie to None it is replaced with NaN.\r\n\r\nSame thing with `s.loc['dd'] = None`\n\n### Expected Behavior\n\nIt should stay None\n\n### Installed Versions\n\n<details>\r\n>>> pd.show_versions()\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 9a607e2afa549a9295db09ad05df6572c1a85542\r\npython           : 3.8.13.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.6.0\r\nVersion          : Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.6.0.dev0+165.g9a607e2afa\r\nnumpy            : 1.22.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\nsetuptools       : 56.0.0\r\npip              : 22.0.4\r\nCython           : 0.29.32\r\npytest           : 6.2.5\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 7.16.1\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : 0.8.7\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : 3.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : 0.3.5\r\nscipy            : 1.5.4\r\nsnappy           : None\r\nsqlalchemy       : 1.4.32\r\ntables           : None\r\ntabulate         : 0.8.9\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48665/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48664",
    "id": 1379725110,
    "node_id": "I_kwDOAA0YD85SPO82",
    "number": 48664,
    "title": "BUG: Change in series copy behavior in 1.5",
    "user": {
      "login": "anthonyaag",
      "id": 6341861,
      "node_id": "MDQ6VXNlcjYzNDE4NjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6341861?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/anthonyaag",
      "html_url": "https://github.com/anthonyaag",
      "followers_url": "https://api.github.com/users/anthonyaag/followers",
      "following_url": "https://api.github.com/users/anthonyaag/following{/other_user}",
      "gists_url": "https://api.github.com/users/anthonyaag/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/anthonyaag/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/anthonyaag/subscriptions",
      "organizations_url": "https://api.github.com/users/anthonyaag/orgs",
      "repos_url": "https://api.github.com/users/anthonyaag/repos",
      "events_url": "https://api.github.com/users/anthonyaag/events{/privacy}",
      "received_events_url": "https://api.github.com/users/anthonyaag/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 2085877452,
        "node_id": "MDU6TGFiZWwyMDg1ODc3NDUy",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Copy%20/%20view%20semantics",
        "name": "Copy / view semantics",
        "color": "70e5ca",
        "default": false,
        "description": ""
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 4,
    "created_at": "2022-09-20T16:59:05Z",
    "updated_at": "2022-09-20T22:36:14Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\nser1 = pd.Series([1,2,3,4])\r\nser2 = pd.Series(ser1)\r\nser3 = pd.Series(ser1, index=ser1.index)\r\nprint(ser1.index is ser2.index)\r\nprint(ser1.index is ser3.index)\r\nprint(ser1._mgr is ser2._mgr)\r\nprint(ser1._mgr is ser3._mgr)\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nHi All! \r\n\r\nVery excited to use pandas==1.5.0 but noticed this change. Not sure if its intentional as part of some of the series refactoring \r\n\r\nIn pandas 1.4.4 all of the above return true but in pandas 1.5.0 `ser1._mgr is ser3._mgr` returns False which is unexpected \r\n\r\nNow when passed an index kwarg, that generates a new SingleBlockManager, but before 1.5 it didn't. \r\n\r\n### Expected Behavior\r\n\r\nIn [1]: import pandas as pd\r\n\r\nIn [2]: ser1 = pd.Series([1,2,3,4])\r\n   ...: ser2 = pd.Series(ser1)\r\n   ...: ser3 = pd.Series(ser1, index=ser1.index)\r\n   ...: print(ser1.index is ser2.index)\r\n   ...: print(ser1.index is ser3.index)\r\n   ...: print(ser1._mgr is ser2._mgr)\r\n   ...: print(ser1._mgr is ser3._mgr)\r\nTrue\r\nTrue\r\nTrue\r\nTrue\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.10.7.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.4.117.hrtdev\r\nVersion          : #3 SMP Tue May 11 13:44:03 EDT 2021\r\nmachine          : x86_64\r\nprocessor        :\r\nbyteorder        : little\r\nLC_ALL           :\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.23.2\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 62.1.0\r\npip              : 22.2.2\r\nCython           : 0.29.30\r\npytest           : 7.1.2\r\nhypothesis       : 6.52.3\r\nsphinx           : 5.0.2\r\nblosc            : 1.10.6\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : 1.1\r\npymysql          : 1.0.2\r\npsycopg2         : 2.9.3\r\njinja2           : 3.1.2\r\nIPython          : 8.4.0\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : 1.3.5\r\nbrotli           : 1.0.9\r\nfastparquet      : 0.8.1\r\nfsspec           : 2022.5.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.2\r\nnumba            : 0.56.2\r\nnumexpr          : 2.8.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.10\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : 1.0.9\r\ns3fs             : None\r\nscipy            : 1.9.1\r\nsnappy           : None\r\nsqlalchemy       : 1.4.39\r\ntables           : 3.7.0\r\ntabulate         : 0.8.10\r\nxarray           : 2022.6.0\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : 0.18.0\r\ntzdata           : 2022.1\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48664/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48663",
    "id": 1379721552,
    "node_id": "I_kwDOAA0YD85SPOFQ",
    "number": 48663,
    "title": "CI: Unpin hypothesis in wheel builds",
    "user": {
      "login": "phofl",
      "id": 61934744,
      "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/phofl",
      "html_url": "https://github.com/phofl",
      "followers_url": "https://api.github.com/users/phofl/followers",
      "following_url": "https://api.github.com/users/phofl/following{/other_user}",
      "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
      "organizations_url": "https://api.github.com/users/phofl/orgs",
      "repos_url": "https://api.github.com/users/phofl/repos",
      "events_url": "https://api.github.com/users/phofl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/phofl/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 48070600,
        "node_id": "MDU6TGFiZWw0ODA3MDYwMA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/CI",
        "name": "CI",
        "color": "a2bca7",
        "default": false,
        "description": "Continuous Integration"
      },
      {
        "id": 527603109,
        "node_id": "MDU6TGFiZWw1Mjc2MDMxMDk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Dependencies",
        "name": "Dependencies",
        "color": "d93f0b",
        "default": false,
        "description": "Required and optional dependencies"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T16:56:30Z",
    "updated_at": "2022-09-20T16:56:38Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "The new hypothesis tested limits more strictly causing some build failures.\r\n\r\nWe pinned the version in our wheel build process.\r\n\r\nsee https://github.com/pandas-dev/pandas/pull/47952",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48663/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48662",
    "id": 1379715591,
    "node_id": "PR_kwDOAA0YD84_Smxk",
    "number": 48662,
    "title": "BUG: Series.getitem not falling back to positional for bool index",
    "user": {
      "login": "phofl",
      "id": 61934744,
      "node_id": "MDQ6VXNlcjYxOTM0NzQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/61934744?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/phofl",
      "html_url": "https://github.com/phofl",
      "followers_url": "https://api.github.com/users/phofl/followers",
      "following_url": "https://api.github.com/users/phofl/following{/other_user}",
      "gists_url": "https://api.github.com/users/phofl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/phofl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/phofl/subscriptions",
      "organizations_url": "https://api.github.com/users/phofl/orgs",
      "repos_url": "https://api.github.com/users/phofl/repos",
      "events_url": "https://api.github.com/users/phofl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/phofl/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 2822098,
        "node_id": "MDU6TGFiZWwyODIyMDk4",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Indexing",
        "name": "Indexing",
        "color": "0b02e1",
        "default": false,
        "description": "Related to indexing on series/frames, not to indexes themselves"
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 0,
    "created_at": "2022-09-20T16:51:14Z",
    "updated_at": "2022-09-20T16:51:14Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48662",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48662",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48662.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48662.patch",
      "merged_at": null
    },
    "body": "- [x] closes #48653 (Replace xxxx with the Github issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\ncc @jbrockmendel ",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48662/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48661",
    "id": 1379691873,
    "node_id": "PR_kwDOAA0YD84_Sh6b",
    "number": 48661,
    "title": "REF: support reso in remaining tslibs helpers",
    "user": {
      "login": "jbrockmendel",
      "id": 8078968,
      "node_id": "MDQ6VXNlcjgwNzg5Njg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbrockmendel",
      "html_url": "https://github.com/jbrockmendel",
      "followers_url": "https://api.github.com/users/jbrockmendel/followers",
      "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
      "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
      "repos_url": "https://api.github.com/users/jbrockmendel/repos",
      "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 127681,
        "node_id": "MDU6TGFiZWwxMjc2ODE=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Refactor",
        "name": "Refactor",
        "color": "FCE94F",
        "default": false,
        "description": "Internal refactoring of code"
      },
      {
        "id": 3713792788,
        "node_id": "LA_kwDOAA0YD87dW_sU",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Non-Nano",
        "name": "Non-Nano",
        "color": "006b75",
        "default": false,
        "description": "datetime64/timedelta64 with non-nanosecond resolution"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T16:31:25Z",
    "updated_at": "2022-09-20T18:48:58Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48661",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48661",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48661.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48661.patch",
      "merged_at": null
    },
    "body": "Mostly just to trim the diff in upcoming PRs.",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48661/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48660",
    "id": 1379667590,
    "node_id": "PR_kwDOAA0YD84_Sc4Y",
    "number": 48660,
    "title": "Fix Excel-specific border styles",
    "user": {
      "login": "tehunter",
      "id": 7980666,
      "node_id": "MDQ6VXNlcjc5ODA2NjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7980666?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tehunter",
      "html_url": "https://github.com/tehunter",
      "followers_url": "https://api.github.com/users/tehunter/followers",
      "following_url": "https://api.github.com/users/tehunter/following{/other_user}",
      "gists_url": "https://api.github.com/users/tehunter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tehunter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tehunter/subscriptions",
      "organizations_url": "https://api.github.com/users/tehunter/orgs",
      "repos_url": "https://api.github.com/users/tehunter/repos",
      "events_url": "https://api.github.com/users/tehunter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tehunter/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 49254273,
        "node_id": "MDU6TGFiZWw0OTI1NDI3Mw==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Excel",
        "name": "IO Excel",
        "color": "bfe5bf",
        "default": false,
        "description": "read_excel, to_excel"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-09-20T16:11:02Z",
    "updated_at": "2022-09-20T18:49:19Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48660",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48660",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48660.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48660.patch",
      "merged_at": null
    },
    "body": "- [X] closes #48649 \r\n- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [X] ~Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.~\r\n- [X] Added an entry in the latest `doc/source/whatsnew/v1.5.1.rst` file if fixing a bug or adding a new feature.\r\n\r\nFixes Excel-specific border styles and modifies behavior when `border-style` provided without a `border-color` to match CSS behavior (i.e., defaults to black)",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48660/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48659",
    "id": 1379661331,
    "node_id": "PR_kwDOAA0YD84_SblE",
    "number": 48659,
    "title": "BUG: DatetimeIndex ignoring explicit tz=None",
    "user": {
      "login": "jbrockmendel",
      "id": 8078968,
      "node_id": "MDQ6VXNlcjgwNzg5Njg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8078968?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jbrockmendel",
      "html_url": "https://github.com/jbrockmendel",
      "followers_url": "https://api.github.com/users/jbrockmendel/followers",
      "following_url": "https://api.github.com/users/jbrockmendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/jbrockmendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jbrockmendel/subscriptions",
      "organizations_url": "https://api.github.com/users/jbrockmendel/orgs",
      "repos_url": "https://api.github.com/users/jbrockmendel/repos",
      "events_url": "https://api.github.com/users/jbrockmendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jbrockmendel/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 60458168,
        "node_id": "MDU6TGFiZWw2MDQ1ODE2OA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Timezones",
        "name": "Timezones",
        "color": "5319e7",
        "default": false,
        "description": "Timezone data dtype"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-09-20T16:05:55Z",
    "updated_at": "2022-09-20T20:29:23Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48659",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48659",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48659.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48659.patch",
      "merged_at": null
    },
    "body": "- [ ] closes #xxxx (Replace xxxx with the Github issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48659/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48658",
    "id": 1379449377,
    "node_id": "I_kwDOAA0YD85SOLoh",
    "number": 48658,
    "title": "BUILD: Getting Syntax error for pandas library import in python If not using virtual env",
    "user": {
      "login": "gmmkmtgk",
      "id": 51493190,
      "node_id": "MDQ6VXNlcjUxNDkzMTkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/51493190?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gmmkmtgk",
      "html_url": "https://github.com/gmmkmtgk",
      "followers_url": "https://api.github.com/users/gmmkmtgk/followers",
      "following_url": "https://api.github.com/users/gmmkmtgk/following{/other_user}",
      "gists_url": "https://api.github.com/users/gmmkmtgk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gmmkmtgk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gmmkmtgk/subscriptions",
      "organizations_url": "https://api.github.com/users/gmmkmtgk/orgs",
      "repos_url": "https://api.github.com/users/gmmkmtgk/repos",
      "events_url": "https://api.github.com/users/gmmkmtgk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gmmkmtgk/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 129350,
        "node_id": "MDU6TGFiZWwxMjkzNTA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Build",
        "name": "Build",
        "color": "75507B",
        "default": false,
        "description": "Library building on various platforms"
      },
      {
        "id": 307649777,
        "node_id": "MDU6TGFiZWwzMDc2NDk3Nzc=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info",
        "name": "Needs Info",
        "color": "207de5",
        "default": false,
        "description": "Clarification about behavior needed to assess issue"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-09-20T13:43:52Z",
    "updated_at": "2022-09-20T18:36:13Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Installation check\n\n- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).\n\n\n### Platform\n\nWindows-10-10.0.19044-SP0\n\n### Installation Method\n\npip install\n\n### pandas Version\n\nlatest\n\n### Python Version\n\n3.10.6\n\n### Installation Logs\n\nIf I use virtual env then everything is fine But if I run simply then getting syntax error for any kind of library import\r\n\r\nConsider a simple pandas library import program\r\n\r\n`import pandas as pd\r\n\r\n\r\n\r\n\r\nC:\\Users\\Keshav\\Desktop\\GAN_Assignment>python main.py\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Keshav\\Desktop\\GAN_Assignment\\main.py\", line 1, in <module>\r\n    import pandas as pd\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\__init__.py\", line 22, in <module>\r\n    from pandas.compat import is_numpy_dev as _is_numpy_dev\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\compat\\__init__.py\", line 15, in <module>      \r\n    from pandas.compat.numpy import (\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\compat\\numpy\\__init__.py\", line 4, in <module> \r\n    from pandas.util.version import Version\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\util\\__init__.py\", line 1, in <module>\r\n    from pandas.util._decorators import (  # noqa:F401\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\util\\_decorators.py\", line 14, in <module>     \r\n    from pandas._libs.properties import cache_readonly  # noqa:F401\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\_libs\\__init__.py\", line 13, in <module>       \r\n    from pandas._libs.interval import Interval\r\n  File \"pandas\\_libs\\interval.pyx\", line 1, in init pandas._libs.interval\r\n  File \"pandas\\_libs\\hashtable.pyx\", line 1, in init pandas._libs.hashtable\r\n  File \"pandas\\_libs\\missing.pyx\", line 1, in init pandas._libs.missing\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pandas\\_libs\\tslibs\\__init__.py\", line 30, in <module>\r\n    from pandas._libs.tslibs.conversion import (\r\n  File \"pandas\\_libs\\tslibs\\conversion.pyx\", line 1, in init pandas._libs.tslibs.conversion\r\n  File \"pandas\\_libs\\tslibs\\timezones.pyx\", line 14, in init pandas._libs.tslibs.timezones\r\n  File \"C:\\Users\\Keshav\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\dateutil\\tz.py\", line 78\r\n    `self._name`,\r\n    ^\r\nSyntaxError: invalid syntax`\r\n\r\n![16b8583075ed5ab039e26ab7c6f49777160b4f53](https://user-images.githubusercontent.com/51493190/191273640-6f105e3a-bc29-495e-80b1-029e28ce607a.png)\r\n\r\n\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48658/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48657",
    "id": 1379238241,
    "node_id": "I_kwDOAA0YD85SNYFh",
    "number": 48657,
    "title": "BUG: indexing with `at` and  Multi-index gives unexpected error",
    "user": {
      "login": "lschwetlick",
      "id": 12753726,
      "node_id": "MDQ6VXNlcjEyNzUzNzI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/12753726?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lschwetlick",
      "html_url": "https://github.com/lschwetlick",
      "followers_url": "https://api.github.com/users/lschwetlick/followers",
      "following_url": "https://api.github.com/users/lschwetlick/following{/other_user}",
      "gists_url": "https://api.github.com/users/lschwetlick/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lschwetlick/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lschwetlick/subscriptions",
      "organizations_url": "https://api.github.com/users/lschwetlick/orgs",
      "repos_url": "https://api.github.com/users/lschwetlick/repos",
      "events_url": "https://api.github.com/users/lschwetlick/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lschwetlick/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2022-09-20T11:11:09Z",
    "updated_at": "2022-09-20T14:34:19Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\nqwe = pd.DataFrame({\"b\":[3,4,5], \"n\":[5,4,3], \"a\":[3,4,5], \"c\":[5,4,3]})\r\nqwe.columns = pd.MultiIndex.from_tuples([(\"A\", \"b\"),(\"A\", \"n\"),(\"B\", \"a\"),(\"B\", \"c\")])\r\nqwe[\"q\"] = \"asd\"\r\n# demo of getter error\r\nprint(f\" 'loc' getter works fine for qwe.at[0, ('A', 'n')] {qwe.loc[0, ('A', 'n')]}\")\r\nprint(f\" 'at' getter works fine for qwe.at[0, ('A', 'n')] {qwe.at[0, ('A', 'n')]}\")\r\nprint(f\" 'loc' getter works fine for qwe.loc[0, 'q'] {qwe.loc[0, 'q']}\")\r\nprint(f\" 'at' getter doesnt work for qwe.at[0, 'q'] {qwe.at[0, 'q']}\")\r\n#demo of setter error\r\nqwe.at[0, (\"A\", \"n\")] = 6 # Works fine!\r\nqwe.at[0, \"q\"] = 6 # Works fine!\r\nqwe.at[0, \"q\"] = [9,8,7] # Error\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nGiven a dataframe with a multiindex, I can index individual cells using `at`. I would expect the indexing to work analogously to `loc`. I have encountered some related errors:\r\n1. getting an individual cell with `at` doesn't work when the second level of the multi-index is empty. This is okay to do in `loc`. i.e. `qwe.at[0, 'q']` for getting does not work is the second level of q is empty, but for `qwe.loc[0, 'q']` it works.\r\n2. The same kind of indexing using `at` for setting does *not* produce an error when *setting* a scalar, i.e. `qwe.at[0, 'q']=5` is ok\r\n3. The same kind of indexing using `at` for setting does produce an error when setting a list, i.e. `qwe.at[0, 'q']=[1,2,3]` is not ok\r\n\r\n<img width=\"297\" alt=\"Screenshot 2022-09-20 at 16 30 17\" src=\"https://user-images.githubusercontent.com/12753726/191285637-d60ea33e-0223-4fae-aa7f-5723ce387252.png\">\r\n\r\n\r\n### Expected Behavior\r\n\r\nI would expect `at` to work analogously to `loc` for indexing and for the getters and setters to either both work or both not work. I would also expect to be able to insert lists into a cell, even when the dataframe has a multiindex.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.10.3.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.4.0\r\nVersion          : Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : en_US.UTF-8\r\nLANG             : None\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.22.4\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 58.1.0\r\npip              : 22.1.2\r\nCython           : None\r\npytest           : 7.1.2\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : 8.4.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.2\r\nnumba            : 0.55.2\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.1\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : 2022.3.0\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\nClear Cell Output\r\nConvert to Markdown Cell\r\nDelete Cell\r\nAdd Cell Above\r\nAdd Cell Below\r\nVisibility\r\nInput\r\nOutput\r\nExtended Output\r\nParameterized Cell\r\n1\r\n​\r\n\r\nClear Cell Output\r\nConvert to Markdown Cell\r\nDelete Cell\r\nAdd Cell Above\r\nAdd Cell Below\r\nVisibility\r\nInput\r\nOutput\r\nExtended Output\r\nParameterized Cell\r\n1\r\n​\r\n​\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48657/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48656",
    "id": 1379098065,
    "node_id": "I_kwDOAA0YD85SM13R",
    "number": 48656,
    "title": "REGR: df.apply('any', axis=1) fails with ValueError",
    "user": {
      "login": "vnlitvinov",
      "id": 45396231,
      "node_id": "MDQ6VXNlcjQ1Mzk2MjMx",
      "avatar_url": "https://avatars.githubusercontent.com/u/45396231?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vnlitvinov",
      "html_url": "https://github.com/vnlitvinov",
      "followers_url": "https://api.github.com/users/vnlitvinov/followers",
      "following_url": "https://api.github.com/users/vnlitvinov/following{/other_user}",
      "gists_url": "https://api.github.com/users/vnlitvinov/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vnlitvinov/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vnlitvinov/subscriptions",
      "organizations_url": "https://api.github.com/users/vnlitvinov/orgs",
      "repos_url": "https://api.github.com/users/vnlitvinov/repos",
      "events_url": "https://api.github.com/users/vnlitvinov/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vnlitvinov/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      },
      {
        "id": 697792067,
        "node_id": "MDU6TGFiZWw2OTc3OTIwNjc=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Apply",
        "name": "Apply",
        "color": "fbca04",
        "default": false,
        "description": "Apply, Aggregate, Transform"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2022-09-20T09:24:41Z",
    "updated_at": "2022-09-20T16:38:43Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\ndf = pd.DataFrame({'a': [0, 1]})\r\nprint(df.apply('any', axis=1))\n```\n\n\n### Issue Description\n\nWhen running the snippet above, pandas 1.5 produces the following stack trace:\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Users\\Vass\\.conda\\envs\\pandas\\lib\\site-packages\\pandas\\core\\frame.py\", line 9558, in apply\r\n    return op.apply().__finalize__(self, method=\"apply\")\r\n  File \"C:\\Users\\Vass\\.conda\\envs\\pandas\\lib\\site-packages\\pandas\\core\\apply.py\", line 720, in apply\r\n    return self.apply_str()\r\n  File \"C:\\Users\\Vass\\.conda\\envs\\pandas\\lib\\site-packages\\pandas\\core\\apply.py\", line 923, in apply_str\r\n    return super().apply_str()\r\n  File \"C:\\Users\\Vass\\.conda\\envs\\pandas\\lib\\site-packages\\pandas\\core\\apply.py\", line 556, in apply_str\r\n    raise ValueError(f\"Operation {f} does not support axis=1\")\r\nValueError: Operation any does not support axis=1\r\n```\r\n\r\nI believe the root cause is this chunk of code:\r\nhttps://github.com/pandas-dev/pandas/blob/c68a96f6994a1c4a3e684669b293b5ae37634f2c/pandas/core/apply.py#L550-L556\r\n\r\nwhich should get the signature of `pandas.DataFrame.any` but, as `.any()` is decorated:\r\nhttps://github.com/pandas-dev/pandas/blob/c68a96f6994a1c4a3e684669b293b5ae37634f2c/pandas/core/generic.py#L11629-L11647\r\n\r\nit gets the signature of the _decorator function_ instead.\n\n### Expected Behavior\n\nThe snippet above is printing the following when run on pandas 1.4.4:\r\n\r\n```\r\n0    False\r\n1     True\r\ndtype: bool\r\n```\r\n\r\nI believe it should print the same on 1.5.x, too.\n\n### Installed Versions\n\n<details>\r\n<summary>pd.show_versions()</summary>\r\n\r\n```\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.8.13.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.22000\r\nmachine          : AMD64\r\nprocessor        : AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : Russian_Russia.1251\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.23.3\r\npytz             : 2022.2.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 65.3.0\r\npip              : 22.2.2\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n```\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48656/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48654",
    "id": 1379015895,
    "node_id": "I_kwDOAA0YD85SMhzX",
    "number": 48654,
    "title": "ENH: Safety net for operations not compatible with a given dtype. ",
    "user": {
      "login": "adrienpacifico",
      "id": 6614121,
      "node_id": "MDQ6VXNlcjY2MTQxMjE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6614121?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/adrienpacifico",
      "html_url": "https://github.com/adrienpacifico",
      "followers_url": "https://api.github.com/users/adrienpacifico/followers",
      "following_url": "https://api.github.com/users/adrienpacifico/following{/other_user}",
      "gists_url": "https://api.github.com/users/adrienpacifico/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/adrienpacifico/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/adrienpacifico/subscriptions",
      "organizations_url": "https://api.github.com/users/adrienpacifico/orgs",
      "repos_url": "https://api.github.com/users/adrienpacifico/repos",
      "events_url": "https://api.github.com/users/adrienpacifico/events{/privacy}",
      "received_events_url": "https://api.github.com/users/adrienpacifico/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 31404521,
        "node_id": "MDU6TGFiZWwzMTQwNDUyMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions",
        "name": "Dtype Conversions",
        "color": "e102d8",
        "default": false,
        "description": "Unexpected or buggy dtype conversions"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 3,
    "created_at": "2022-09-20T08:23:30Z",
    "updated_at": "2022-09-20T22:32:50Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Feature Type\r\n\r\n- [X] Adding new functionality to pandas\r\n\r\n- [X] Changing existing functionality in pandas\r\n\r\n- [ ] Removing existing functionality in pandas\r\n\r\n\r\n### Problem Description\r\n\r\nI wish I could have a safety net preventing me from doing non correct operations linked to dtypes issues/incompatibilities.\r\n\r\nExample:\r\n```python\r\nIn [1]: import pandas as pd\r\nIn [2]: s = pd.Series([1,3,5,129]).astype(\"uint8\")\r\n   ...: s + s\r\n\r\nOut[2]: \r\n0     2\r\n1     6\r\n2    10\r\n3     2\r\ndtype: uint8\r\n```\r\nThe expected value of 129+129 would be 258, however  the value is 2.\r\nThis is because the maximum value of an \"uint8\" is 255, and 255+1 set the value back to zero. \r\n\r\nAnother kind of misleading behaviour is if one uses astype in a not careful way\r\n\r\n```python\r\nIn [1]: import pandas as pd\r\nIn [2]: s = pd.Series([1,-1,10**5]).astype(\"int8\")\r\nIn [3]: s\r\n\r\nOut[3]: \r\n0     1\r\n1    -1\r\n2   -96\r\ndtype: int8\r\n```\r\n\r\n\r\n### Feature Description\r\n\r\nA solution could be to make sure that an operation is compatible between columns dtypes.\r\nI try to show an example of what I mean for the `+` operation.\r\n\r\n```python \r\n    @unpack_zerodim_and_defer(\"__add__\")\r\n    def __add__(self, other):\r\n        check_dtype_operation_add(self, other)       # The check function checking that an operation is ok\r\n        return self._arith_method(other, operator.add)\r\n````\r\nA mock of the function testing only for an operation between uint8 and a number:\r\n```python\r\ndef check_dtype_operation_add(self, other):\r\n    if self.dtype == \"uint8\" and isinstance(other, numbers.Number) :\r\n        logging.warning(\"warning: you are performing an addition between a uint8 and a number,\"\r\n                        \"this could result in an overflow if the operation leads to number greater than 255\"\r\n        )\r\n        if self.max() + other > 255:\r\n            raise Exception(f\"adding {self.dtype} with a number which had lead to a memory overflow, please upcast your series dtype\")\r\n\r\n```\r\n\r\nThe final behaviour is this one:\r\n- print a warning (should be kept for low values dtypes (int8, uint8, Int8, float8, etc))\r\n- raise an exception if the operation leads to an overflow\r\n```python\r\nIn [1]: import pandas as pd\r\n\r\nIn [2]: s = pd.Series([1,2,200]).astype(\"uint8\")\r\n\r\nIn [3]: s+200\r\nWARNING:root:warning: your are performing an addition between a uint8 and a number,this could result in an overflow if the operation leads to number greater than 255\r\n---------------------------------------------------------------------------\r\nException                                 Traceback (most recent call last)\r\nCell In [3], line 1\r\n----> 1 s+200\r\n\r\nFile /workspaces/pandas/pandas/core/ops/common.py:73, in _unpack_zerodim_and_defer.<locals>.new_method(self, other)\r\n     69             return NotImplemented\r\n     71 other = item_from_zerodim(other)\r\n---> 73 return method(self, other)\r\n\r\nFile /workspaces/pandas/pandas/core/arraylike.py:121, in OpsMixin.__add__(self, other)\r\n    119 @unpack_zerodim_and_defer(\"__add__\")\r\n    120 def __add__(self, other):\r\n--> 121     check_dtype_operation_add(self, other)\r\n    122     return self._arith_method(other, operator.add)\r\n\r\nFile /workspaces/pandas/pandas/core/arraylike.py:43, in check_dtype_operation_add(self, other)\r\n     39 logging.warning(\"warning: your are performing an addition between a uint8 and a number,\"\r\n     40                 \"this could result in an overflow if the operation leads to number greater than 255\"\r\n     41 )\r\n     42 if self.max() + other > 255:\r\n---> 43     raise Exception(f\"adding {self.dtype} with a number which had lead to a memory overflow, please upcast your series dtype\")\r\n     44 else:\r\n     45     pass\r\n\r\nException: adding uint8 with a number which had lead to a memory overflow, please upcast your series dtype\r\n```\r\n\r\nConcerning `.astype` we would just have to make sure, in the case of a downcasting, that `s.max()` and `s.min()` are compatible  with the lower dtype.\r\n\r\nI guess that would impact slightly the performance, an option to deactivate this behaviour ( e.g. `pd.options.dtype.dtype_checks = False` ) could solve the issue for users that want the maximum performance.\r\n\r\n### Alternative Solutions\r\n\r\nAnother solution would be to upcast implicitly the dtype when needed. I actually would enjoy that solution, it could possibly be implemented as an option `pd.options.dytpe.automatic_casting = True`\r\n\r\n```python\r\nIn [1]: import pandas as pd\r\nIn [2]: s = pd.Series([1,3,5,129]).astype(\"uint8\")\r\n   ...: s + s\r\n\r\nOut[2]: \r\n0     2\r\n1     6\r\n2    10\r\n3     258\r\ndtype: uint16\r\n```\r\n\r\n```python\r\nIn [1]: import pandas as pd\r\nIn [2]: s = pd.Series([1,3,5,129, 3.2]).astype(\"uint8\")\r\n   ...: s\r\n\r\nOut[3]: \r\n0      1.0\r\n1      3.0\r\n2      5.0\r\n3    129.0\r\n4      3.2\r\ndtype: float64\r\n```\r\nOne could also imagine an option to save the maximum memory `pd.options.dytpe.automatic_casting = \"aggressive\"`\r\n\r\n\r\n```python\r\nIn [1]: import pandas as pd\r\nIn [2]: s = pd.Series([1,3,5,129, 3.2]).astype(\"uint8\")\r\n   ...: s\r\n\r\nOut[3]: \r\n0      1.000000\r\n1      3.000000\r\n2      5.000000\r\n3    129.000000\r\n4      3.199219\r\ndtype: float16\r\n```\r\n\r\n\r\n\r\n\r\n### Additional Context\r\n\r\n### My experience & why I think something should be done\r\nWhile I know about this pandas behavior since 2014, I remember that I was fairly surprised the first time it happened to me.\r\nI was working on a 2000 columns dataframe, with more than 2000 lines of code, my downstream dataframe was strange, and I spent a great amount of time finding the issue.\r\n\r\nI am certain that users wanting to save a little memory space with lower dtypes have faced (silently or not) the same issue, and I am pretty sure that production code is running bugs due to this.  Moreover, the **documentation lacks warnings** about it.\r\n\r\n### Documentation concerning the subject:\r\nI looked at several places to find a warning about this pandas behaviour, and I did not find anything.\r\n\r\n#### API Reference:\r\n- https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.add.html or any other operation reference this possible issue.\r\n- https://pandas.pydata.org/pandas-docs/version/1.5/reference/arrays.html does not reference the issue\r\nnor the\r\n- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html?highlight=astype#pandas.DataFrame.astype\r\n\r\nIt is the same for the Series part of the api reference.\r\n\r\n#### User guide \r\nThe [basics dtypes](https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes) is fairly complete, but except for an example that shows explicitly the issue, the is no warning in the whole guide about possible issues with operations or downcasting that would lead to unintended behaviour. \r\n\r\n#### Functions docstring\r\nI was not able to find any warning in the function docstring about this issue. ",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48654/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48653",
    "id": 1378959755,
    "node_id": "I_kwDOAA0YD85SMUGL",
    "number": 48653,
    "title": "QST: pd.series indexing True auto 0 change",
    "user": {
      "login": "sc303030",
      "id": 52574837,
      "node_id": "MDQ6VXNlcjUyNTc0ODM3",
      "avatar_url": "https://avatars.githubusercontent.com/u/52574837?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sc303030",
      "html_url": "https://github.com/sc303030",
      "followers_url": "https://api.github.com/users/sc303030/followers",
      "following_url": "https://api.github.com/users/sc303030/following{/other_user}",
      "gists_url": "https://api.github.com/users/sc303030/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sc303030/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sc303030/subscriptions",
      "organizations_url": "https://api.github.com/users/sc303030/orgs",
      "repos_url": "https://api.github.com/users/sc303030/repos",
      "events_url": "https://api.github.com/users/sc303030/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sc303030/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 2822098,
        "node_id": "MDU6TGFiZWwyODIyMDk4",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Indexing",
        "name": "Indexing",
        "color": "0b02e1",
        "default": false,
        "description": "Related to indexing on series/frames, not to indexes themselves"
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2022-09-20T07:37:26Z",
    "updated_at": "2022-09-20T16:46:05Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Research\n\n- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.\n\n- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).\n\n\n### Link to question on StackOverflow\n\nhttps://stackoverflow.com/questions/73783112/1-4-4-other-1-5-0-pd-series-indexing-true-auto-0-change\n\n### Question about pandas\n\n```python\r\ntest = pd.Series({True: 0, False: 0})\r\n\r\n1.4.4\r\nprint(test[0])\r\n> 0\r\n\r\nbut \r\n1.5.0\r\nprint(test[True])\r\n\r\n> keyerror 0\r\n```\r\n\r\n1.4.4 and 1.5.0 What has changed?I can't find it",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48653/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48652",
    "id": 1378773381,
    "node_id": "I_kwDOAA0YD85SLmmF",
    "number": 48652,
    "title": "BUG: the rolling.Rolling subclass cannot handle string when using apply function",
    "user": {
      "login": "shuimei",
      "id": 16859022,
      "node_id": "MDQ6VXNlcjE2ODU5MDIy",
      "avatar_url": "https://avatars.githubusercontent.com/u/16859022?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shuimei",
      "html_url": "https://github.com/shuimei",
      "followers_url": "https://api.github.com/users/shuimei/followers",
      "following_url": "https://api.github.com/users/shuimei/following{/other_user}",
      "gists_url": "https://api.github.com/users/shuimei/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shuimei/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shuimei/subscriptions",
      "organizations_url": "https://api.github.com/users/shuimei/orgs",
      "repos_url": "https://api.github.com/users/shuimei/repos",
      "events_url": "https://api.github.com/users/shuimei/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shuimei/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T03:43:00Z",
    "updated_at": "2022-09-20T03:43:39Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\ndf = pd.DataFrame({\"aqi_level\": [\"优\"] * 20 + [\"良\"] * 20})\r\ndf.rolling(4).apply(lambda a: len(list(a)))\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nthe example code raise a DataError\r\nDataError: No numeric types to aggregate\r\n```python\r\n---------------------------------------------------------------------------\r\nDataError                                 Traceback (most recent call last)\r\nInput In [6], in <cell line: 1>()\r\n----> 1 df.rolling(4).apply(lambda a: len(a))\r\n\r\nFile /home/software/conda/lib/python3.9/site-packages/pandas/core/window/rolling.py:2000, in Rolling.apply(self, func, raw, engine, engine_kwargs, args, kwargs)\r\n   1979 @doc(\r\n   1980     template_header,\r\n   1981     create_section_header(\"Parameters\"),\r\n   (...)\r\n   1998     kwargs: dict[str, Any] | None = None,\r\n   1999 ):\r\n-> 2000     return super().apply(\r\n   2001         func,\r\n   2002         raw=raw,\r\n   2003         engine=engine,\r\n   2004         engine_kwargs=engine_kwargs,\r\n   2005         args=args,\r\n   2006         kwargs=kwargs,\r\n   2007     )\r\n\r\nFile /home/software/conda/lib/python3.9/site-packages/pandas/core/window/rolling.py:1422, in RollingAndExpandingMixin.apply(self, func, raw, engine, engine_kwargs, args, kwargs)\r\n   1419 else:\r\n   1420     raise ValueError(\"engine must be either 'numba' or 'cython'\")\r\n-> 1422 return self._apply(\r\n   1423     apply_func,\r\n   1424     name=\"apply\",\r\n   1425     numba_args=numba_args,\r\n   1426 )\r\n\r\nFile /home/software/conda/lib/python3.9/site-packages/pandas/core/window/rolling.py:663, in BaseWindow._apply(self, func, name, numeric_only, numba_args, **kwargs)\r\n    660     return result\r\n    662 if self.method == \"single\":\r\n--> 663     return self._apply_blockwise(homogeneous_func, name, numeric_only)\r\n    664 else:\r\n    665     return self._apply_tablewise(homogeneous_func, name, numeric_only)\r\n\r\nFile /home/software/conda/lib/python3.9/site-packages/pandas/core/window/rolling.py:555, in BaseWindow._apply_blockwise(self, homogeneous_func, name, numeric_only)\r\n    545     dropped = obj.columns.difference(obj.columns.take(taker))\r\n    546     warnings.warn(\r\n    547         \"Dropping of nuisance columns in rolling operations \"\r\n    548         \"is deprecated; in a future version this will raise TypeError. \"\r\n   (...)\r\n    552         stacklevel=find_stack_level(inspect.currentframe()),\r\n    553     )\r\n--> 555 return self._resolve_output(df, obj)\r\n\r\nFile /home/software/conda/lib/python3.9/site-packages/pandas/core/window/rolling.py:450, in BaseWindow._resolve_output(self, out, obj)\r\n    448 \"\"\"Validate and finalize result.\"\"\"\r\n    449 if out.shape[1] == 0 and obj.shape[1] > 0:\r\n--> 450     raise DataError(\"No numeric types to aggregate\")\r\n    451 elif out.shape[1] == 0:\r\n    452     return obj.astype(\"float64\")\r\n\r\nDataError: No numeric types to aggregate\r\n```\r\n\r\n### Expected Behavior\r\n\r\njust like a single groupby apply function, output a length of every group/rolling\r\n\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 224458ee25d92ccdf289d1ae2741d178df4f323e\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 3.10.0-327.el7.x86_64\r\nVersion          : #1 SMP Thu Nov 19 22:10:57 UTC 2015\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : zh_CN.UTF-8\r\nLOCALE           : zh_CN.UTF-8\r\n\r\npandas           : 1.5.0rc0\r\nnumpy            : 1.21.2\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\nsetuptools       : 58.0.4\r\npip              : 21.2.4\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.1.1\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : 1.3.4\r\nbrotli           :\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : 0.55.1\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : 3.0.10\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsnappy           : None\r\nsqlalchemy       : 1.4.13\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48652/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48650",
    "id": 1378690745,
    "node_id": "I_kwDOAA0YD85SLSa5",
    "number": 48650,
    "title": "ENH: return current class name in deprecate_nonkeyword_arguments",
    "user": {
      "login": "twoertwein",
      "id": 6618166,
      "node_id": "MDQ6VXNlcjY2MTgxNjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6618166?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/twoertwein",
      "html_url": "https://github.com/twoertwein",
      "followers_url": "https://api.github.com/users/twoertwein/followers",
      "following_url": "https://api.github.com/users/twoertwein/following{/other_user}",
      "gists_url": "https://api.github.com/users/twoertwein/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/twoertwein/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/twoertwein/subscriptions",
      "organizations_url": "https://api.github.com/users/twoertwein/orgs",
      "repos_url": "https://api.github.com/users/twoertwein/repos",
      "events_url": "https://api.github.com/users/twoertwein/events{/privacy}",
      "received_events_url": "https://api.github.com/users/twoertwein/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76812,
        "node_id": "MDU6TGFiZWw3NjgxMg==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement",
        "name": "Enhancement",
        "color": "4E9A06",
        "default": false,
        "description": null
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-20T01:14:27Z",
    "updated_at": "2022-09-20T16:49:26Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "```py\r\nclass A:\r\n    @deprecate_nonkeyword_arguments(version=None, allowed_args=[\"self\"])\r\n    def method(self, deprecated_positional=None): ...\r\n\r\nclass B(A): ...\r\n\r\nB().method(1)  # will warn about `A.method`\r\n```\r\nMight be nice to warn about `B.method`  https://github.com/pandas-dev/pandas/pull/48592#discussion_r974747938\r\n\r\n\r\nCould probably use something like `args[0].__class__.__name__` inside the decorator but that assumes that the decorated object is a method and not a function.",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48650/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48649",
    "id": 1378571679,
    "node_id": "I_kwDOAA0YD85SK1Wf",
    "number": 48649,
    "title": "BUG: `df.to_excel` fails for `\"border-style: hair\"` with `xlsxwriter`",
    "user": {
      "login": "tehunter",
      "id": 7980666,
      "node_id": "MDQ6VXNlcjc5ODA2NjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7980666?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tehunter",
      "html_url": "https://github.com/tehunter",
      "followers_url": "https://api.github.com/users/tehunter/followers",
      "following_url": "https://api.github.com/users/tehunter/following{/other_user}",
      "gists_url": "https://api.github.com/users/tehunter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tehunter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tehunter/subscriptions",
      "organizations_url": "https://api.github.com/users/tehunter/orgs",
      "repos_url": "https://api.github.com/users/tehunter/repos",
      "events_url": "https://api.github.com/users/tehunter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tehunter/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 49254273,
        "node_id": "MDU6TGFiZWw0OTI1NDI3Mw==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Excel",
        "name": "IO Excel",
        "color": "bfe5bf",
        "default": false,
        "description": "read_excel, to_excel"
      },
      {
        "id": 1728592794,
        "node_id": "MDU6TGFiZWwxNzI4NTkyNzk0",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Styler",
        "name": "Styler",
        "color": "006b75",
        "default": false,
        "description": "conditional formatting using DataFrame.style"
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "tehunter",
      "id": 7980666,
      "node_id": "MDQ6VXNlcjc5ODA2NjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7980666?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tehunter",
      "html_url": "https://github.com/tehunter",
      "followers_url": "https://api.github.com/users/tehunter/followers",
      "following_url": "https://api.github.com/users/tehunter/following{/other_user}",
      "gists_url": "https://api.github.com/users/tehunter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tehunter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tehunter/subscriptions",
      "organizations_url": "https://api.github.com/users/tehunter/orgs",
      "repos_url": "https://api.github.com/users/tehunter/repos",
      "events_url": "https://api.github.com/users/tehunter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tehunter/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "tehunter",
        "id": 7980666,
        "node_id": "MDQ6VXNlcjc5ODA2NjY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7980666?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/tehunter",
        "html_url": "https://github.com/tehunter",
        "followers_url": "https://api.github.com/users/tehunter/followers",
        "following_url": "https://api.github.com/users/tehunter/following{/other_user}",
        "gists_url": "https://api.github.com/users/tehunter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/tehunter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tehunter/subscriptions",
        "organizations_url": "https://api.github.com/users/tehunter/orgs",
        "repos_url": "https://api.github.com/users/tehunter/repos",
        "events_url": "https://api.github.com/users/tehunter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/tehunter/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 6,
    "created_at": "2022-09-19T22:00:40Z",
    "updated_at": "2022-09-20T16:12:33Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\n\r\ndf = pd.DataFrame({\"a\": [1]})\r\nstyler = df.style.applymap(lambda x: \"border-style: hair; border-color: black\")\r\n\r\nstyler.to_excel(r\"test_border.xlsx\", engine=\"xlsxwriter\")\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\nThe `CSSToExcelConverter._border_style` function does not return any value (i.e., None) when the style string is not recognized. However, \"hair\" should be a recognized style string in xlsxwriter, corresponding to [border index \"7\"](https://xlsxwriter.readthedocs.io/format.html#set_border). This leads to a crash in `xlsxwriter`. Moreover, there is no path to actually return the \"hair\" style for any engine.\r\n\r\n### Expected Behavior\r\n\r\nUse of `border-style: hair` will export a spreadsheet with the correct formatting.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 224458ee25d92ccdf289d1ae2741d178df4f323e\r\npython           : 3.10.4.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.5.0rc0\r\nnumpy            : 1.21.6\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 63.4.1\r\npip              : 22.1.2\r\nCython           : None\r\npytest           : 7.1.2\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.3\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.1.2\r\nIPython          : 8.4.0\r\npandas_datareader: None\r\nbs4              : 4.11.1\r\nbottleneck       : 1.3.5\r\nbrotli           : None\r\nfastparquet      : 0.5.0\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumba            : 0.55.2\r\nnumexpr          : 2.8.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.10\r\npandas_gbq       : None\r\npyarrow          : 8.0.0\r\npyreadstat       : 1.1.9\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48649/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48645",
    "id": 1378521119,
    "node_id": "I_kwDOAA0YD85SKpAf",
    "number": 48645,
    "title": "BUG: `dropna` affects `observed` in `DataFrame.groupby()` since v1.5 ",
    "user": {
      "login": "pwwang",
      "id": 1188067,
      "node_id": "MDQ6VXNlcjExODgwNjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1188067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pwwang",
      "html_url": "https://github.com/pwwang",
      "followers_url": "https://api.github.com/users/pwwang/followers",
      "following_url": "https://api.github.com/users/pwwang/following{/other_user}",
      "gists_url": "https://api.github.com/users/pwwang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pwwang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pwwang/subscriptions",
      "organizations_url": "https://api.github.com/users/pwwang/orgs",
      "repos_url": "https://api.github.com/users/pwwang/repos",
      "events_url": "https://api.github.com/users/pwwang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pwwang/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 233160,
        "node_id": "MDU6TGFiZWwyMzMxNjA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Groupby",
        "name": "Groupby",
        "color": "729FCF",
        "default": false,
        "description": null
      },
      {
        "id": 32815646,
        "node_id": "MDU6TGFiZWwzMjgxNTY0Ng==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Regression",
        "name": "Regression",
        "color": "e11d21",
        "default": false,
        "description": "Functionality that used to work in a prior pandas version"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "rhshadrach",
      "id": 45562402,
      "node_id": "MDQ6VXNlcjQ1NTYyNDAy",
      "avatar_url": "https://avatars.githubusercontent.com/u/45562402?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rhshadrach",
      "html_url": "https://github.com/rhshadrach",
      "followers_url": "https://api.github.com/users/rhshadrach/followers",
      "following_url": "https://api.github.com/users/rhshadrach/following{/other_user}",
      "gists_url": "https://api.github.com/users/rhshadrach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rhshadrach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rhshadrach/subscriptions",
      "organizations_url": "https://api.github.com/users/rhshadrach/orgs",
      "repos_url": "https://api.github.com/users/rhshadrach/repos",
      "events_url": "https://api.github.com/users/rhshadrach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rhshadrach/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "rhshadrach",
        "id": 45562402,
        "node_id": "MDQ6VXNlcjQ1NTYyNDAy",
        "avatar_url": "https://avatars.githubusercontent.com/u/45562402?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rhshadrach",
        "html_url": "https://github.com/rhshadrach",
        "followers_url": "https://api.github.com/users/rhshadrach/followers",
        "following_url": "https://api.github.com/users/rhshadrach/following{/other_user}",
        "gists_url": "https://api.github.com/users/rhshadrach/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rhshadrach/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rhshadrach/subscriptions",
        "organizations_url": "https://api.github.com/users/rhshadrach/orgs",
        "repos_url": "https://api.github.com/users/rhshadrach/repos",
        "events_url": "https://api.github.com/users/rhshadrach/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rhshadrach/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 2,
    "created_at": "2022-09-19T21:06:02Z",
    "updated_at": "2022-09-20T21:34:29Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [ ] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\n### Reproducible Example\r\n\r\n```python\r\n# With pandas 1.5\r\n\r\nfrom pandas import DataFrame, Categorical\r\n\r\ndf = DataFrame({\"x\": Categorical([1, 2], categories=[1, 2, 3]), \"y\": [3, 4]})\r\n\r\ndf.groupby(\"x\", observed=False).grouper.result_index\r\n# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n\r\ndf.groupby(\"x\", observed=False, dropna=False).grouper.result_index\r\n# CategoricalIndex([1, 2], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n# ------------------------------------------------------------------------------------------\r\n# Unexpected result ↑\r\n\r\ndf.groupby(\"x\", observed=False, dropna=True).grouper.result_index\r\n# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n\r\n\r\n# With pandas 1.4.4 and prior\r\n\r\ndf.groupby(\"x\", observed=False).grouper.result_index\r\n# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n\r\ndf.groupby(\"x\", observed=False, dropna=False).grouper.result_index\r\n# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n\r\ndf.groupby(\"x\", observed=False, dropna=True).grouper.result_index\r\n# CategoricalIndex([1, 2, 3], categories=[1, 2, 3], ordered=False, dtype='category', name='x')\r\n```\r\n\r\n\r\n### Issue Description\r\n\r\n`dropna=False` in `DataFrame.groupby()` should not affect the results when `observed=False`.\r\n\r\n### Expected Behavior\r\n\r\nExpected the behavior with pandas 1.4.4 and prior.\r\n\r\n### Installed Versions\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 87cfe4e38bafe7300a6003a1d18bd80f3f77c763\r\npython           : 3.9.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.15.57.1-microsoft-standard-WSL2\r\nVersion          : #1 SMP Wed Jul 27 02:20:31 UTC 2022\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.5.0\r\nnumpy            : 1.23.3\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 58.0.0\r\npip              : 22.2.2\r\nCython           : None\r\npytest           : 6.2.5\r\nhypothesis       : None\r\nsphinx           : 4.5.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.6.3\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.1.2\r\nIPython          : 8.1.1\r\npandas_datareader: None\r\nbs4              : 4.9.3\r\nbottleneck       : None\r\nbrotli           : \r\nfastparquet      : None\r\nfsspec           : 2022.02.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : 0.53.1\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : 3.0.8\r\npandas_gbq       : None\r\npyarrow          : 7.0.0\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsnappy           : None\r\nsqlalchemy       : 1.4.28\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48645/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48644",
    "id": 1378501871,
    "node_id": "I_kwDOAA0YD85SKkTv",
    "number": 48644,
    "title": "DOC: Sticky Headers in Table Visualization is broken in v1.5.0",
    "user": {
      "login": "tehunter",
      "id": 7980666,
      "node_id": "MDQ6VXNlcjc5ODA2NjY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7980666?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tehunter",
      "html_url": "https://github.com/tehunter",
      "followers_url": "https://api.github.com/users/tehunter/followers",
      "following_url": "https://api.github.com/users/tehunter/following{/other_user}",
      "gists_url": "https://api.github.com/users/tehunter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tehunter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tehunter/subscriptions",
      "organizations_url": "https://api.github.com/users/tehunter/orgs",
      "repos_url": "https://api.github.com/users/tehunter/repos",
      "events_url": "https://api.github.com/users/tehunter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tehunter/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 1728592794,
        "node_id": "MDU6TGFiZWwxNzI4NTkyNzk0",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Styler",
        "name": "Styler",
        "color": "006b75",
        "default": false,
        "description": "conditional formatting using DataFrame.style"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "WooilKim",
      "id": 30896089,
      "node_id": "MDQ6VXNlcjMwODk2MDg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/30896089?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WooilKim",
      "html_url": "https://github.com/WooilKim",
      "followers_url": "https://api.github.com/users/WooilKim/followers",
      "following_url": "https://api.github.com/users/WooilKim/following{/other_user}",
      "gists_url": "https://api.github.com/users/WooilKim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WooilKim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WooilKim/subscriptions",
      "organizations_url": "https://api.github.com/users/WooilKim/orgs",
      "repos_url": "https://api.github.com/users/WooilKim/repos",
      "events_url": "https://api.github.com/users/WooilKim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WooilKim/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "WooilKim",
        "id": 30896089,
        "node_id": "MDQ6VXNlcjMwODk2MDg5",
        "avatar_url": "https://avatars.githubusercontent.com/u/30896089?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/WooilKim",
        "html_url": "https://github.com/WooilKim",
        "followers_url": "https://api.github.com/users/WooilKim/followers",
        "following_url": "https://api.github.com/users/WooilKim/following{/other_user}",
        "gists_url": "https://api.github.com/users/WooilKim/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/WooilKim/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/WooilKim/subscriptions",
        "organizations_url": "https://api.github.com/users/WooilKim/orgs",
        "repos_url": "https://api.github.com/users/WooilKim/repos",
        "events_url": "https://api.github.com/users/WooilKim/events{/privacy}",
        "received_events_url": "https://api.github.com/users/WooilKim/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98",
      "html_url": "https://github.com/pandas-dev/pandas/milestone/98",
      "labels_url": "https://api.github.com/repos/pandas-dev/pandas/milestones/98/labels",
      "id": 8438761,
      "node_id": "MI_kwDOAA0YD84AgMPp",
      "number": 98,
      "title": "1.5.1",
      "description": "on-merge: backport to 1.5.x",
      "creator": {
        "login": "datapythonista",
        "id": 10058240,
        "node_id": "MDQ6VXNlcjEwMDU4MjQw",
        "avatar_url": "https://avatars.githubusercontent.com/u/10058240?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/datapythonista",
        "html_url": "https://github.com/datapythonista",
        "followers_url": "https://api.github.com/users/datapythonista/followers",
        "following_url": "https://api.github.com/users/datapythonista/following{/other_user}",
        "gists_url": "https://api.github.com/users/datapythonista/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/datapythonista/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/datapythonista/subscriptions",
        "organizations_url": "https://api.github.com/users/datapythonista/orgs",
        "repos_url": "https://api.github.com/users/datapythonista/repos",
        "events_url": "https://api.github.com/users/datapythonista/events{/privacy}",
        "received_events_url": "https://api.github.com/users/datapythonista/received_events",
        "type": "User",
        "site_admin": false
      },
      "open_issues": 19,
      "closed_issues": 6,
      "state": "open",
      "created_at": "2022-09-19T20:12:38Z",
      "updated_at": "2022-09-20T20:55:02Z",
      "due_on": null,
      "closed_at": null
    },
    "comments": 5,
    "created_at": "2022-09-19T20:45:16Z",
    "updated_at": "2022-09-20T10:03:28Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\n\n\n### Location of the documentation\n\nhttps://pandas.pydata.org/pandas-docs/version/1.5.0/user_guide/style.html#Sticky-Headers\n\n### Documentation problem\n\nHere is how the DataFrame looks in v1.5.0 documentation:\r\n![image](https://user-images.githubusercontent.com/7980666/191111779-c618f44a-3f8e-4735-84bc-a15bb16df0d1.png)\r\n\r\nHere is how it looked in v1.4.4 documentation:\r\n![image](https://user-images.githubusercontent.com/7980666/191111849-c4a606af-dccd-4063-96ae-d6f25fd6e1d1.png)\r\n\r\nI'm using Firefox 104\n\n### Suggested fix for documentation\n\nIt seems that `pydata-sphinx-theme.css`  is applying `width: fit-content;` to all tables. This should be overridden for this wide table.\r\n\r\nThis seems to be related to #48285",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48644/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48638",
    "id": 1378007387,
    "node_id": "I_kwDOAA0YD85SIrlb",
    "number": 48638,
    "title": "BUG: StringArray is a subclass of PandasArray",
    "user": {
      "login": "ehsantn",
      "id": 2333645,
      "node_id": "MDQ6VXNlcjIzMzM2NDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2333645?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ehsantn",
      "html_url": "https://github.com/ehsantn",
      "followers_url": "https://api.github.com/users/ehsantn/followers",
      "following_url": "https://api.github.com/users/ehsantn/following{/other_user}",
      "gists_url": "https://api.github.com/users/ehsantn/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ehsantn/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ehsantn/subscriptions",
      "organizations_url": "https://api.github.com/users/ehsantn/orgs",
      "repos_url": "https://api.github.com/users/ehsantn/repos",
      "events_url": "https://api.github.com/users/ehsantn/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ehsantn/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 49094459,
        "node_id": "MDU6TGFiZWw0OTA5NDQ1OQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Internals",
        "name": "Internals",
        "color": "fbca04",
        "default": false,
        "description": "Related to non-user accessible pandas implementation"
      },
      {
        "id": 57522093,
        "node_id": "MDU6TGFiZWw1NzUyMjA5Mw==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Strings",
        "name": "Strings",
        "color": "5319e7",
        "default": false,
        "description": "String extension data type and string data"
      },
      {
        "id": 849023693,
        "node_id": "MDU6TGFiZWw4NDkwMjM2OTM=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray",
        "name": "ExtensionArray",
        "color": "6138b5",
        "default": false,
        "description": "Extending pandas with custom dtypes or arrays."
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 4,
    "created_at": "2022-09-19T13:59:18Z",
    "updated_at": "2022-09-21T00:55:58Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nIn [2]: A = pd.array([\"a1\", \"a2\"], dtype=\"string\")\r\n\r\nIn [3]: A\r\nOut[3]:\r\n<StringArray>\r\n['a1', 'a2']\r\nLength: 2, dtype: string\r\n\r\nIn [4]: isinstance(A, pd.arrays.StringArray)\r\nOut[4]: True\r\n\r\nIn [5]: isinstance(A, pd.arrays.PandasArray)\r\nOut[5]: True\n```\n\n\n### Issue Description\n\nPandasArray is described as a thin wrapper around Numpy values for internal compatibility. However, StringArray is a subclass of PandasArray for some reason (other ExtensionArrays are not). This inconsistency causes issues for unboxing the values for Bodo JIT (and I assume other systems consuming Pandas data).\r\n\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Series.array.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.arrays.PandasArray.html\n\n### Expected Behavior\n\nOutput of `isinstance(pd.array([\"a1\", \"a2\"], dtype=\"string\"), pd.arrays.PandasArray)` should be False.\n\n### Installed Versions\n\n<details>\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : bf856a85a3b769821809ff456e288542af16310c\r\npython           : 3.9.6.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 21.2.0\r\nVersion          : Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.6.0.dev0+145.gbf856a85a3\r\nnumpy            : 1.21.1\r\npytz             : 2021.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 49.6.0.post20210108\r\npip              : 21.2.2\r\nCython           : 0.29.32\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : 7.26.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nbrotli           :\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\ntzdata           : None\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48638/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637/events",
    "html_url": "https://github.com/pandas-dev/pandas/pull/48637",
    "id": 1377706232,
    "node_id": "PR_kwDOAA0YD84_L6an",
    "number": 48637,
    "title": "BUG: Fixed DataFrame.__repr__ Type Error when column dtype is np.record (GH 48526)",
    "user": {
      "login": "RaphSku",
      "id": 45042665,
      "node_id": "MDQ6VXNlcjQ1MDQyNjY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/45042665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/RaphSku",
      "html_url": "https://github.com/RaphSku",
      "followers_url": "https://api.github.com/users/RaphSku/followers",
      "following_url": "https://api.github.com/users/RaphSku/following{/other_user}",
      "gists_url": "https://api.github.com/users/RaphSku/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/RaphSku/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/RaphSku/subscriptions",
      "organizations_url": "https://api.github.com/users/RaphSku/orgs",
      "repos_url": "https://api.github.com/users/RaphSku/repos",
      "events_url": "https://api.github.com/users/RaphSku/events{/privacy}",
      "received_events_url": "https://api.github.com/users/RaphSku/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 13101118,
        "node_id": "MDU6TGFiZWwxMzEwMTExOA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting",
        "name": "Output-Formatting",
        "color": "ededed",
        "default": false,
        "description": "__repr__ of pandas objects, to_string"
      },
      {
        "id": 2189479765,
        "node_id": "MDU6TGFiZWwyMTg5NDc5NzY1",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Nested%20Data",
        "name": "Nested Data",
        "color": "f2f989",
        "default": false,
        "description": "Data where the values are collections (lists, sets, dicts, objects, etc.)."
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 0,
    "created_at": "2022-09-19T10:03:21Z",
    "updated_at": "2022-09-20T10:24:54Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/pulls/48637",
      "html_url": "https://github.com/pandas-dev/pandas/pull/48637",
      "diff_url": "https://github.com/pandas-dev/pandas/pull/48637.diff",
      "patch_url": "https://github.com/pandas-dev/pandas/pull/48637.patch",
      "merged_at": null
    },
    "body": "- [x] closes #48526\r\n- [x] [Tests added and passed]\r\n- [x] All [code checks passed]\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v1.6.0.rst` file if fixing a bug or adding a new feature.\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48637/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48635",
    "id": 1377620676,
    "node_id": "I_kwDOAA0YD85SHNLE",
    "number": 48635,
    "title": "DOC: `value_counts` description doesn't match code logic",
    "user": {
      "login": "maciejskorski",
      "id": 31315784,
      "node_id": "MDQ6VXNlcjMxMzE1Nzg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/31315784?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maciejskorski",
      "html_url": "https://github.com/maciejskorski",
      "followers_url": "https://api.github.com/users/maciejskorski/followers",
      "following_url": "https://api.github.com/users/maciejskorski/following{/other_user}",
      "gists_url": "https://api.github.com/users/maciejskorski/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/maciejskorski/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/maciejskorski/subscriptions",
      "organizations_url": "https://api.github.com/users/maciejskorski/orgs",
      "repos_url": "https://api.github.com/users/maciejskorski/repos",
      "events_url": "https://api.github.com/users/maciejskorski/events{/privacy}",
      "received_events_url": "https://api.github.com/users/maciejskorski/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 57296398,
        "node_id": "MDU6TGFiZWw1NzI5NjM5OA==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Algos",
        "name": "Algos",
        "color": "eb6420",
        "default": false,
        "description": "Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff"
      },
      {
        "id": 1954720290,
        "node_id": "MDU6TGFiZWwxOTU0NzIwMjkw",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage",
        "name": "Needs Triage",
        "color": "0052cc",
        "default": false,
        "description": "Issue that has not been reviewed by a pandas team member"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "WooilKim",
      "id": 30896089,
      "node_id": "MDQ6VXNlcjMwODk2MDg5",
      "avatar_url": "https://avatars.githubusercontent.com/u/30896089?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/WooilKim",
      "html_url": "https://github.com/WooilKim",
      "followers_url": "https://api.github.com/users/WooilKim/followers",
      "following_url": "https://api.github.com/users/WooilKim/following{/other_user}",
      "gists_url": "https://api.github.com/users/WooilKim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/WooilKim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/WooilKim/subscriptions",
      "organizations_url": "https://api.github.com/users/WooilKim/orgs",
      "repos_url": "https://api.github.com/users/WooilKim/repos",
      "events_url": "https://api.github.com/users/WooilKim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/WooilKim/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "WooilKim",
        "id": 30896089,
        "node_id": "MDQ6VXNlcjMwODk2MDg5",
        "avatar_url": "https://avatars.githubusercontent.com/u/30896089?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/WooilKim",
        "html_url": "https://github.com/WooilKim",
        "followers_url": "https://api.github.com/users/WooilKim/followers",
        "following_url": "https://api.github.com/users/WooilKim/following{/other_user}",
        "gists_url": "https://api.github.com/users/WooilKim/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/WooilKim/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/WooilKim/subscriptions",
        "organizations_url": "https://api.github.com/users/WooilKim/orgs",
        "repos_url": "https://api.github.com/users/WooilKim/repos",
        "events_url": "https://api.github.com/users/WooilKim/events{/privacy}",
        "received_events_url": "https://api.github.com/users/WooilKim/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 8,
    "created_at": "2022-09-19T08:51:04Z",
    "updated_at": "2022-09-20T08:25:39Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\r\n\r\n\r\n### Location of the documentation\r\n\r\n[dev docs](https://pandas.pydata.org/docs/dev/reference/api/pandas.DataFrame.value_counts.html)\r\n\r\n[last release docs](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html)\r\n\r\n### Documentation problem\r\n\r\n`value_counts` utility incorrectly claims counting \"unique rows\", respectively \"unique combinations\".\r\n\r\nIn reality, it only does `groupby` followed by `size`, no `nunique`:\r\n\r\nhttps://github.com/pandas-dev/pandas/blob/ca60aab7340d9989d9428e11a51467658190bb6b/pandas/core/frame.py#L6468-L6592\r\n\r\n### Suggested fix for documentation\r\n\r\nAlign the doc string to match the code logic.\r\n\r\nI suggest not to mention \"unique rows\" or \"unique combinations\" and maybe mention the equivalence to `groupby`+`size` with the optional `normalization`.\r\n\r\nWill be happy to submit a PR for that, or share my two cents in the discussion. ",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48635/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48633",
    "id": 1377587028,
    "node_id": "I_kwDOAA0YD85SHE9U",
    "number": 48633,
    "title": "BUG: guessing datetime format fails with 200622-12-31",
    "user": {
      "login": "MarcoGorelli",
      "id": 33491632,
      "node_id": "MDQ6VXNlcjMzNDkxNjMy",
      "avatar_url": "https://avatars.githubusercontent.com/u/33491632?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MarcoGorelli",
      "html_url": "https://github.com/MarcoGorelli",
      "followers_url": "https://api.github.com/users/MarcoGorelli/followers",
      "following_url": "https://api.github.com/users/MarcoGorelli/following{/other_user}",
      "gists_url": "https://api.github.com/users/MarcoGorelli/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MarcoGorelli/subscriptions",
      "organizations_url": "https://api.github.com/users/MarcoGorelli/orgs",
      "repos_url": "https://api.github.com/users/MarcoGorelli/repos",
      "events_url": "https://api.github.com/users/MarcoGorelli/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MarcoGorelli/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 76811,
        "node_id": "MDU6TGFiZWw3NjgxMQ==",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Bug",
        "name": "Bug",
        "color": "e10c02",
        "default": false,
        "description": null
      },
      {
        "id": 211840,
        "node_id": "MDU6TGFiZWwyMTE4NDA=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries",
        "name": "Timeseries",
        "color": "AFEEEE",
        "default": false,
        "description": null
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2022-09-19T08:24:55Z",
    "updated_at": "2022-09-19T08:26:21Z",
    "closed_at": null,
    "author_association": "MEMBER",
    "active_lock_reason": null,
    "body": "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\npd.to_datetime([\"200622-12-31\", \"111111-24-11\"], errors='coerce', infer_datetime_format=True)\n```\n\n\n### Issue Description\n\n```\r\nTraceback (most recent call last):\r\n  File \"t.py\", line 7, in <module>\r\n    pd.to_datetime([\"200622-12-31\", \"111111-24-11\"], errors='coerce', infer_datetime_format=True)\r\n  File \"/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py\", line 1124, in to_datetime\r\n    result = convert_listlike(argc, format)\r\n  File \"/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py\", line 418, in _convert_listlike_datetimes\r\n    format = _guess_datetime_format_for_array(arg, dayfirst=dayfirst)\r\n  File \"/home/marcogorelli/pandas-dev/pandas/core/tools/datetimes.py\", line 132, in _guess_datetime_format_for_array\r\n    return guess_datetime_format(arr[non_nan_elements[0]], dayfirst=dayfirst)\r\n  File \"pandas/_libs/tslibs/parsing.pyx\", line 1029, in pandas._libs.tslibs.parsing.guess_datetime_format\r\n    tokens[offset_index] = parsed_datetime.strftime(\"%z\")\r\nValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).\r\n```\r\n\r\nNote that this is different from https://github.com/pandas-dev/pandas/issues/46071, because here the error happens when pandas is still guessing the format\n\n### Expected Behavior\n\n```\r\nDatetimeIndex(['NaT', 'NaT'], dtype='datetime64[ns]', freq=None)\r\n```\n\n### Installed Versions\n\n<details>\r\n\r\nReplace this line with the output of pd.show_versions()\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : bf856a85a3b769821809ff456e288542af16310c\r\npython           : 3.8.13.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.10.16.3-microsoft-standard-WSL2\r\nVersion          : #1 SMP Fri Apr 2 22:23:49 UTC 2021\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_GB.UTF-8\r\nLOCALE           : en_GB.UTF-8\r\n\r\npandas           : 1.6.0.dev0+145.gbf856a85a3\r\nnumpy            : 1.22.4\r\npytz             : 2022.2.1\r\ndateutil         : 2.8.2\r\nsetuptools       : 65.3.0\r\npip              : 22.2.2\r\nCython           : 0.29.32\r\npytest           : 7.1.3\r\nhypothesis       : 6.54.5\r\nsphinx           : 4.5.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.3\r\nlxml.etree       : 4.9.1\r\nhtml5lib         : 1.1\r\npymysql          : 1.0.2\r\npsycopg2         : 2.9.3\r\njinja2           : 3.0.3\r\nIPython          : 8.5.0\r\npandas_datareader: 0.10.0\r\nbs4              : 4.11.1\r\nbottleneck       : 1.3.5\r\nbrotli           : \r\nfastparquet      : 0.8.3\r\nfsspec           : 2021.11.0\r\ngcsfs            : 2021.11.0\r\nmatplotlib       : 3.5.3\r\nnumba            : 0.55.2\r\nnumexpr          : 2.8.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.10\r\npandas_gbq       : 0.17.8\r\npyarrow          : 9.0.0\r\npyreadstat       : 1.1.9\r\npyxlsb           : 1.0.9\r\ns3fs             : 2021.11.0\r\nscipy            : 1.9.1\r\nsnappy           : \r\nsqlalchemy       : 1.4.41\r\ntables           : 3.7.0\r\ntabulate         : 0.8.10\r\nxarray           : 2022.6.0\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nzstandard        : 0.18.0\r\ntzdata           : None\r\nNone\r\n\r\n\r\n</details>\r\n",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48633/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  {
    "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632",
    "repository_url": "https://api.github.com/repos/pandas-dev/pandas",
    "labels_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632/labels{/name}",
    "comments_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632/comments",
    "events_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632/events",
    "html_url": "https://github.com/pandas-dev/pandas/issues/48632",
    "id": 1377466457,
    "node_id": "I_kwDOAA0YD85SGnhZ",
    "number": 48632,
    "title": "DOC: GL08 errors in pandas.Timestamp",
    "user": {
      "login": "Sherry3",
      "id": 28356592,
      "node_id": "MDQ6VXNlcjI4MzU2NTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/28356592?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sherry3",
      "html_url": "https://github.com/Sherry3",
      "followers_url": "https://api.github.com/users/Sherry3/followers",
      "following_url": "https://api.github.com/users/Sherry3/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sherry3/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sherry3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sherry3/subscriptions",
      "organizations_url": "https://api.github.com/users/Sherry3/orgs",
      "repos_url": "https://api.github.com/users/Sherry3/repos",
      "events_url": "https://api.github.com/users/Sherry3/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sherry3/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 134699,
        "node_id": "MDU6TGFiZWwxMzQ2OTk=",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Docs",
        "name": "Docs",
        "color": "3465A4",
        "default": false,
        "description": null
      },
      {
        "id": 3877216987,
        "node_id": "LA_kwDOAA0YD87nGaLb",
        "url": "https://api.github.com/repos/pandas-dev/pandas/labels/Timestamp",
        "name": "Timestamp",
        "color": "5DE3E8",
        "default": false,
        "description": "pd.Timestamp and associated methods"
      }
    ],
    "state": "open",
    "locked": false,
    "assignee": {
      "login": "Sherry3",
      "id": 28356592,
      "node_id": "MDQ6VXNlcjI4MzU2NTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/28356592?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sherry3",
      "html_url": "https://github.com/Sherry3",
      "followers_url": "https://api.github.com/users/Sherry3/followers",
      "following_url": "https://api.github.com/users/Sherry3/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sherry3/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sherry3/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sherry3/subscriptions",
      "organizations_url": "https://api.github.com/users/Sherry3/orgs",
      "repos_url": "https://api.github.com/users/Sherry3/repos",
      "events_url": "https://api.github.com/users/Sherry3/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sherry3/received_events",
      "type": "User",
      "site_admin": false
    },
    "assignees": [
      {
        "login": "Sherry3",
        "id": 28356592,
        "node_id": "MDQ6VXNlcjI4MzU2NTky",
        "avatar_url": "https://avatars.githubusercontent.com/u/28356592?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Sherry3",
        "html_url": "https://github.com/Sherry3",
        "followers_url": "https://api.github.com/users/Sherry3/followers",
        "following_url": "https://api.github.com/users/Sherry3/following{/other_user}",
        "gists_url": "https://api.github.com/users/Sherry3/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Sherry3/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Sherry3/subscriptions",
        "organizations_url": "https://api.github.com/users/Sherry3/orgs",
        "repos_url": "https://api.github.com/users/Sherry3/repos",
        "events_url": "https://api.github.com/users/Sherry3/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Sherry3/received_events",
        "type": "User",
        "site_admin": false
      }
    ],
    "milestone": null,
    "comments": 7,
    "created_at": "2022-09-19T06:29:52Z",
    "updated_at": "2022-09-20T22:57:01Z",
    "closed_at": null,
    "author_association": "NONE",
    "active_lock_reason": null,
    "body": "### Pandas version checks\r\n\r\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\r\n\r\n\r\n### Location of the documentation\r\n\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.day.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.fold.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.hour.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.microsecond.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.minute.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.month.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.nanosecond.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.second.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.tzinfo.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.value.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.year.html\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.freq.html\r\n\r\n### Documentation problem\r\n\r\nBelow are the GL08 errors in pandas.Timestamp: -\r\n```\r\nNone:None:GL08:pandas.Timestamp.day:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.fold:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.hour:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.microsecond:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.minute:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.month:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.nanosecond:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.second:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.tzinfo:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.value:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.year:The object does not have a docstring\r\nNone:None:GL08:pandas.Timestamp.freq:The object does not have a docstring\r\n```\r\n\r\n### Suggested fix for documentation\r\n\r\nAdding description and examples. Similar to `week`.\r\n\r\nweek | Return the week number of the year.\r\n-- | --\r\n\r\nhttps://pandas.pydata.org/docs/reference/api/pandas.Timestamp.week.html",
    "reactions": {
      "url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/pandas-dev/pandas/issues/48632/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  }
]